### ISSUE TITLE
Warning enumeration value

### ISSUE THREAD

**Issue by mmphego** [sivar2311/SinricClass#1]
Compiling .pioenvs/d1_mini/src/main.cpp.o

In file included from src/main.cpp:3:0:
/home/mmphego/.platformio/lib/Sinric/Sinric.h: In destructor 'SinricClass::~SinricClass()':
/home/mmphego/.platformio/lib/Sinric/Sinric.h:45:12: warning: deleting object of polymorphic class type 'SinricDevice' which has non-virtual destructor might cause u
ndefined behaviour [-Wdelete-non-virtual-dtor]
delete device;
^
/home/mmphego/.platformio/lib/Sinric/Sinric.h: In member function 'void SinricClass::webSocketEvent(WStype_t, uint8_t*, size_t)':
/home/mmphego/.platformio/lib/Sinric/Sinric.h:94:10: warning: enumeration value 'WStype_ERROR' not handled in switch [-Wswitch]
switch (type) {
^
/home/mmphego/.platformio/lib/Sinric/Sinric.h:94:10: warning: enumeration value 'WStype_BIN' not handled in switch [-Wswitch]
/home/mmphego/.platformio/lib/Sinric/Sinric.h:94:10: warning: enumeration value 'WStype_FRAGMENT_TEXT_START' not handled in switch [-Wswitch]
/home/mmphego/.platformio/lib/Sinric/Sinric.h:94:10: warning: enumeration value 'WStype_FRAGMENT_BIN_START' not handled in switch [-Wswitch]
/home/mmphego/.platformio/lib/Sinric/Sinric.h:94:10: warning: enumeration value 'WStype_FRAGMENT' not handled in switch [-Wswitch]
/home/mmphego/.platformio/lib/Sinric/Sinric.h:94:10: warning: enumeration value 'WStype_FRAGMENT_FIN' not handled in switch [-Wswitch]

**Comment by sivar2311** [comment]
These are all warnings but no errors. Most of them are from the websocket library.
Do you have any issues?

**Comment by mmphego** [comment]
Thanks for the great library.

Fixed the warning by adding
```
Default:
    break;
```

**Comment by mmphego** [comment]
Thanks for the great library.

Fixed the warning by adding
```
Default:
    break;
```

**Comment by sivar2311** [comment]
Thanks for pointing! Added in master branch :)
