### ISSUE TITLE
typo in SinricLight.h line 25

### ISSUE THREAD

**Issue by grampy** [sivar2311/SinricClass#5]
Wondered why I never saw onIncColorTemperature event but then discovered:

SinricLight.h line 25

void onIncColorTemperature(IncColorTemperatureCallback callback) { decColorTemperature = callback; }

should of course be 

void onIncColorTemperature(IncColorTemperatureCallback callback) { incColorTemperature = callback; }

**Comment by sivar2311** [comment]
Hi grampy! Thank you!
I never used the ColorTemeperature routines.
It's fixed now.
