### ISSUE TITLE
Update switch state when triggered in code

### ISSUE THREAD

**Issue by Sterling-101** [sivar2311/SinricClass#6]
I've been trying to find a way to update the state of a switch back to Sinric.com but can't seem to work out how to get it to work.
I need to be able to control a set of relays by timer but have the option to override using Sinric so I need it to feed back the state as the timer switches things on an off.

I've had a look in sinricswitch.h but I can't work out how to call the setPowerState from my code?

Any ideas folks?

**Comment by ITMarco93** [comment]
I haven't tried it yet, but you could try to give a shot moving "WebSocketsClient client;" from private to public variables in "Sinric.h", then add to your code:

`
void setPowerStateOnServer(String deviceId, String value) {
  DynamicJsonBuffer jsonBuffer;
  JsonObject& root = jsonBuffer.createObject();
  root["deviceId"] = deviceId;
  root["action"] = "setPowerState";
  root["value"] = value;
  StreamString databuf;
  root.printTo(databuf);
  
  mySwitch.client.sendTXT(databuf);
}
`

**Comment by sivar2311** [comment]
If youre still interested: We're working on a Pro version http://sinric.pro.
Library is available via [github](https://github.com/sinricpro/esp8266-esp32-sdk), Arduino Library Manager, PlatformIO Library Manager.
