### ISSUE TITLE
smart lock

### ISSUE THREAD

**Issue by teohell** [sivar2311/SinricClass#7]
Hi there and thanks for the great work!
I have already implemented some switch and light, but I'm trying to build a alexa-enabled electric lock. There is a device-type in Sinric which shows as "smart lock", but I'm no programmer and I don't know how to add a class to your device library. Would it be possible for you to add it? It would just be "Alexa open :device: " without any other command in it
Thanks!
Matteo

**Comment by sivar2311** [comment]
I need an example code from sinric (kakopapa).

**Comment by sivar2311** [comment]
If youre still interested: We're working on a Pro version http://sinric.pro.
Library is available via [github](https://github.com/sinricpro/esp8266-esp32-sdk), Arduino Library Manager, PlatformIO Library Manager.
