### ISSUE TITLE
TV

### ISSUE THREAD

**Issue by quilimari** [sivar2311/SinricClass#8]
Hello congratulations, very good job
I am triying to select input from TV and Alexa respond me that the device is not responding, I will appreciate if you tell me were to find the valid answer for this command
Also want to know which are the voice commands to change the input
Best regards

**Comment by sivar2311** [comment]
Hi quilimari,

SinricClass have no implementation for TV commands.

Currently we are working on a SinricPro version (https://sinric.pro/).
This will have TV support.

First beta will be released end of October.

Kind regards


Am Fr., 27. Sept. 2019 um 14:40 Uhr schrieb quilimari <
notifications@github.com>:
